import { EvaluationMetric } from "../types";

export const EVALUATION_SUMMARY = {
  holdoutSize: 150,
  reclaimRecoveredCount: 102,
  reclaimRecoveryRate: 68.0,
  reclaimNetRecoveredInr: 1042500, // in rupees
  naiveRecoveredCount: 61,
  naiveRecoveryRate: 40.7,
  naiveNetRecoveredInr: 617500,
  upliftInr: 425000,
  recoveryRateUpliftPercent: 42.0,
  wastedRetriesReductionPercent: 85.0,
  policyBreaches: 0,
  naivePolicyBreaches: 34,
};

export const EVALUATION_BATCH_ITEMS: EvaluationMetric[] = [
  {
    id: "EVAL-001",
    caseId: "EVAL-CASE-01",
    paymentMethod: "UPI (HDFC)",
    amount: 849900,
    failureType: "UPI Timeout",
    naiveAction: "Immediate Blind Retry",
    naiveOutcome: "FAILED",
    reclaimAction: "Delayed Retry (15m backoff)",
    reclaimOutcome: "RECOVERED",
    upliftInr: 849900,
  },
  {
    id: "EVAL-002",
    caseId: "EVAL-CASE-02",
    paymentMethod: "Credit Card (ICICI)",
    amount: 1450000,
    failureType: "Card Decline (3DS)",
    naiveAction: "Immediate Blind Retry x3",
    naiveOutcome: "POLICY_VIOLATION",
    reclaimAction: "Hinglish SMS + UPI QR Link",
    reclaimOutcome: "RECOVERED",
    upliftInr: 1450000,
  },
  {
    id: "EVAL-003",
    caseId: "EVAL-CASE-03",
    paymentMethod: "Credit Card",
    amount: 5500000,
    failureType: "Fraud Signal (Stolen Card)",
    naiveAction: "Blind Auto-Retry",
    naiveOutcome: "WASTED_RETRY",
    reclaimAction: "Deterministic Policy Lock & Stop",
    reclaimOutcome: "PREVENTED_BREACH",
    upliftInr: 0,
  },
  {
    id: "EVAL-004",
    caseId: "EVAL-CASE-04",
    paymentMethod: "Netbanking (SBI)",
    amount: 350000,
    failureType: "Bank Downtime",
    naiveAction: "Immediate Blind Retry",
    naiveOutcome: "FAILED",
    reclaimAction: "Health-Aware Scheduled Retry",
    reclaimOutcome: "RECOVERED",
    upliftInr: 350000,
  },
  {
    id: "EVAL-005",
    caseId: "EVAL-CASE-05",
    paymentMethod: "UPI (Paytm)",
    amount: 120000,
    failureType: "Insufficient Funds",
    naiveAction: "Repeated Blind Debits",
    naiveOutcome: "WASTED_RETRY",
    reclaimAction: "Polite Hinglish SMS Nudge",
    reclaimOutcome: "RECOVERED",
    upliftInr: 120000,
  },
  {
    id: "EVAL-006",
    caseId: "EVAL-CASE-06",
    paymentMethod: "Credit Card (Axis)",
    amount: 1899900,
    failureType: "Checkout Abandonment",
    naiveAction: "No Action",
    naiveOutcome: "FAILED",
    reclaimAction: "WhatsApp 1-Click Cart Link",
    reclaimOutcome: "RECOVERED",
    upliftInr: 1899900,
  },
  {
    id: "EVAL-007",
    caseId: "EVAL-CASE-07",
    paymentMethod: "Debit Card (HDFC)",
    amount: 620000,
    failureType: "Network Drop / Latency Spike",
    naiveAction: "Unbounded Duplicate Retry",
    naiveOutcome: "POLICY_VIOLATION",
    reclaimAction: "Bounded Timeout & Safe Escalation",
    reclaimOutcome: "TIMED_OUT",
    upliftInr: 0,
  },
];
