import { AuditEvent } from "../types";

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "EV-99234",
    timestamp: "29 Aug 2026 14:32:05 IST",
    layer: "LAYER 5",
    source: "VERIFICATION",
    event: "CASE_RESOLVED",
    case: "RC-2024-084",
    desc: "₹18,999 recovered successfully via WhatsApp 1-Click checkout link. Immutable ledger settlement verified.",
    latency: "12ms",
    status: "SUCCESS",
    details: {
      amount: 1899900,
      customer: "Suresh P.",
      gateway: "Razorpay Test Gateway (v1/checkout/link)",
      transactionId: "txn_rz_88294KLS",
      reason: "Customer authorized payment via conversational link.",
      nextAction: "None • Case marked settled",
    },
  },
  {
    id: "EV-99233",
    timestamp: "29 Aug 2026 14:32:04 IST",
    layer: "LAYER 4",
    source: "EXECUTOR",
    event: "ACTION_SUCCEEDED",
    case: "RC-2024-084",
    desc: "Razorpay Webhook payment.captured received for pay_V7bL91qXmZ8. Signature verified.",
    latency: "245ms",
    status: "SUCCESS",
    details: {
      gateway: "Razorpay Test Webhook (payment.captured)",
      transactionId: "pay_V7bL91qXmZ8",
      idempotencyKey: "rz_rec_RC-2024-084_1724922124",
      amount: 1899900,
    },
  },
  {
    id: "EV-99232",
    timestamp: "29 Aug 2026 14:32:02 IST",
    layer: "LAYER 4",
    source: "EXECUTOR",
    event: "ACTION_EXECUTED",
    case: "RC-2024-084",
    desc: "Outbound WhatsApp recovery message dispatched via Gupshup API with idempotency token.",
    latency: "18ms",
    status: "INFO",
    details: {
      gateway: "Gupshup WhatsApp Business API",
      idempotencyKey: "rz_rec_RC-2024-084_1724922124",
      customer: "+91 98333 11223",
    },
  },
  {
    id: "EV-99231",
    timestamp: "29 Aug 2026 14:32:01 IST",
    layer: "LAYER 3",
    source: "POLICY_ENGINE",
    event: "POLICY_APPROVED",
    case: "RC-2024-084",
    desc: "All 6 deterministic policy rules passed. Customer contact limit (1/2) and risk score within thresholds.",
    latency: "3ms",
    status: "SUCCESS",
    details: {
      policyRule: "ALL_RULES_SATISFIED",
      threshold: "6/6 Rules",
      actualValue: "6 Passed (Retry: 0/3, Contact: 1/2, Value: ₹18.99k)",
      nextAction: "Authorize Razorpay / Gupshup dispatch",
    },
  },
  {
    id: "EV-99230",
    timestamp: "29 Aug 2026 14:31:59 IST",
    layer: "LAYER 2",
    source: "AGENT",
    event: "AGENT_DECISION",
    case: "RC-2024-084",
    desc: "AI Engine synthesized recovery plan: Send WhatsApp 1-Click Checkout Link → SMS Nudge → Escalation.",
    latency: "420ms",
    status: "INFO",
    details: {
      reason: "Checkout abandonment with high purchase intent within 2-hour window.",
      nextAction: "Evaluate against Layer 3 Policy Guardrails",
    },
  },
  {
    id: "EV-99229",
    timestamp: "29 Aug 2026 14:31:58 IST",
    layer: "LAYER 1",
    source: "RISK_ENGINE",
    event: "RISK_SCORED",
    case: "RC-2024-084",
    desc: "ML Triage: Recovery probability 0.30, Expected Value ₹5,699. Priority: MEDIUM.",
    latency: "15ms",
    status: "INFO",
    details: {
      amount: 1899900,
      actualValue: "Probability: 30%, Expected: ₹5,699",
      threshold: "Floor: 20%",
    },
  },
  {
    id: "EV-99228",
    timestamp: "29 Aug 2026 14:31:55 IST",
    layer: "LAYER 0",
    source: "AUDIT",
    event: "CASE_CREATED",
    case: "RC-2024-084",
    desc: "Ingested checkout.abandoned event for ₹18,999 from Razorpay standard checkout stream.",
    latency: "8ms",
    status: "INFO",
    details: {
      amount: 1899900,
      paymentMethod: "UPI",
      customer: "Suresh P.",
    },
  },
  {
    id: "EV-99227",
    timestamp: "29 Aug 2026 14:15:02 IST",
    layer: "LAYER 3",
    source: "POLICY_ENGINE",
    event: "POLICY_BLOCKED",
    case: "RC-2024-075",
    desc: "Action blocked by Layer 3: Maximum Retry Count Exceeded (3/3 attempts reached).",
    latency: "2ms",
    status: "BLOCKED",
    details: {
      policyRule: "MAX_RETRY_COUNT",
      threshold: "Max 3 attempts",
      actualValue: "3 attempts recorded",
      reason: "Issuing bank fatigue guardrail engaged.",
      nextAction: "Escalate to Human Operations Desk",
    },
  },
  {
    id: "EV-99226",
    timestamp: "29 Aug 2026 14:15:03 IST",
    layer: "LAYER 5",
    source: "VERIFICATION",
    event: "CASE_ESCALATED",
    case: "RC-2024-075",
    desc: "Case escalated to manual operations desk due to deterministic policy lockout.",
    latency: "10ms",
    status: "BLOCKED",
    details: {
      reason: "Policy blocked automated recovery.",
      nextAction: "Assigned to Human Queue",
    },
  },
  {
    id: "EV-99225",
    timestamp: "29 Aug 2026 13:45:10 IST",
    layer: "LAYER 3",
    source: "POLICY_ENGINE",
    event: "POLICY_BLOCKED",
    case: "RC-2024-044",
    desc: "Action blocked by Layer 3: Fraud / High Risk Signal Detected (Risk Score: 94%).",
    latency: "2ms",
    status: "BLOCKED",
    details: {
      policyRule: "FRAUD_AND_SECURITY_GUARDRAIL",
      threshold: "Max 60% risk score",
      actualValue: "94% risk score from proxy radar",
      reason: "Suspicious transaction characteristics detected.",
      nextAction: "Permanently stop automated recovery",
    },
  },
  {
    id: "EV-99224",
    timestamp: "29 Aug 2026 13:45:11 IST",
    layer: "LAYER 5",
    source: "VERIFICATION",
    event: "CASE_STOPPED",
    case: "RC-2024-044",
    desc: "Autonomous recovery permanently stopped for security. Entity flagged for risk desk review.",
    latency: "8ms",
    status: "BLOCKED",
    details: {
      reason: "Risk radar threshold exceeded.",
      nextAction: "Flag entity in Razorpay Radar Blacklist",
    },
  },
];
