from datetime import datetime, timezone
from uuid import uuid4
from sqlalchemy import Boolean, DateTime, ForeignKey, Index, Integer, String, Text, UniqueConstraint, JSON
from sqlalchemy.orm import Mapped, mapped_column
from .base import Base
def utcnow(): return datetime.now(timezone.utc)
def uid(): return str(uuid4())

class MerchantModel(Base):
    __tablename__="merchants"; id: Mapped[str]=mapped_column(String(64), primary_key=True); business_name: Mapped[str]=mapped_column(String(200)); industry: Mapped[str|None]=mapped_column(String(100)); currency: Mapped[str]=mapped_column(String(3), default="INR"); timezone: Mapped[str]=mapped_column(String(64), default="Asia/Kolkata"); default_language: Mapped[str]=mapped_column(String(32), default="English"); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
class PolicyModel(Base):
    __tablename__="policies"; __table_args__=(UniqueConstraint("merchant_id","version",name="uq_policy_merchant_version"), Index("ix_policy_merchant_active","merchant_id","active")); id: Mapped[str]=mapped_column(String(36), primary_key=True, default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id", ondelete="RESTRICT")); version: Mapped[str]=mapped_column(String(32)); active: Mapped[bool]=mapped_column(Boolean, default=False); configuration: Mapped[dict]=mapped_column(JSON); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); created_by: Mapped[str]=mapped_column(String(100))
class PaymentModel(Base):
    __tablename__="payments"; __table_args__=(UniqueConstraint("merchant_id","external_reference",name="uq_payment_merchant_reference"), Index("ix_payment_merchant_reference","merchant_id","external_reference")); id: Mapped[str]=mapped_column(String(64),primary_key=True); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); external_reference: Mapped[str]=mapped_column(String(128)); amount_minor: Mapped[int]=mapped_column(Integer); currency: Mapped[str]=mapped_column(String(3)); status: Mapped[str]=mapped_column(String(32),default="failed"); payment_method: Mapped[str]=mapped_column(String(64)); failure_type: Mapped[str]=mapped_column(String(64)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,onupdate=utcnow)
class CaseModel(Base):
    __tablename__="cases"; __table_args__=(Index("ix_case_merchant_status","merchant_id","status"),Index("ix_case_merchant_failure","merchant_id","failure_type"),Index("ix_case_merchant_created","merchant_id","created_at")); id: Mapped[str]=mapped_column(String(64),primary_key=True); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); payment_id: Mapped[str]=mapped_column(ForeignKey("payments.id",ondelete="RESTRICT"),unique=True); status: Mapped[str]=mapped_column(String(32)); priority: Mapped[str]=mapped_column(String(16)); failure_type: Mapped[str]=mapped_column(String(64)); recovery_probability: Mapped[float]=mapped_column(); expected_recovery_minor: Mapped[int]=mapped_column(Integer); payload: Mapped[dict]=mapped_column(JSON); retry_count: Mapped[int]=mapped_column(Integer,default=0); contact_count: Mapped[int]=mapped_column(Integer,default=0); recovered_amount_minor: Mapped[int]=mapped_column(Integer,default=0); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,onupdate=utcnow); resolved_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class RecoveryActionModel(Base):
    __tablename__="recovery_actions"; __table_args__=(UniqueConstraint("merchant_id","idempotency_key",name="uq_action_merchant_key"),UniqueConstraint("merchant_id","case_id",name="uq_action_merchant_case"),Index("ix_action_case","case_id"),Index("ix_action_provider_order","merchant_id","provider_order_id"),Index("ix_action_provider_payment","merchant_id","provider_payment_id")); id: Mapped[str]=mapped_column(String(64),primary_key=True); case_id: Mapped[str]=mapped_column(ForeignKey("cases.id",ondelete="RESTRICT")); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); action_type: Mapped[str]=mapped_column(String(64)); status: Mapped[str]=mapped_column(String(32)); idempotency_key: Mapped[str]=mapped_column(String(255)); policy_version: Mapped[str]=mapped_column(String(32)); amount_minor: Mapped[int]=mapped_column(Integer); verification_status: Mapped[str]=mapped_column(String(32)); transaction_id: Mapped[str|None]=mapped_column(String(128)); failure_code: Mapped[str|None]=mapped_column(String(64)); failure_reason: Mapped[str|None]=mapped_column(Text); provider: Mapped[str]=mapped_column(String(32),default="simulated"); provider_order_id: Mapped[str|None]=mapped_column(String(128)); provider_payment_id: Mapped[str|None]=mapped_column(String(128)); provider_status: Mapped[str|None]=mapped_column(String(64)); provider_reference: Mapped[str|None]=mapped_column(String(255)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class CampaignModel(Base):
    __tablename__="campaigns"; __table_args__=(Index("ix_campaign_merchant_status","merchant_id","status"),); id: Mapped[str]=mapped_column(String(64),primary_key=True); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); name: Mapped[str]=mapped_column(String(200)); type: Mapped[str]=mapped_column(String(64)); status: Mapped[str]=mapped_column(String(32)); configuration: Mapped[dict]=mapped_column(JSON); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,onupdate=utcnow); started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); paused_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class CampaignCaseModel(Base):
    __tablename__="campaign_cases"; campaign_id: Mapped[str]=mapped_column(ForeignKey("campaigns.id",ondelete="RESTRICT"),primary_key=True); case_id: Mapped[str]=mapped_column(ForeignKey("cases.id",ondelete="RESTRICT"),primary_key=True); status: Mapped[str]=mapped_column(String(32),default="eligible"); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class CommunicationModel(Base):
    __tablename__="communications"; __table_args__=(Index("ix_communication_case","case_id"),); id: Mapped[str]=mapped_column(String(64),primary_key=True); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); case_id: Mapped[str]=mapped_column(ForeignKey("cases.id",ondelete="RESTRICT")); campaign_id: Mapped[str|None]=mapped_column(ForeignKey("campaigns.id",ondelete="RESTRICT")); channel: Mapped[str]=mapped_column(String(32)); language: Mapped[str]=mapped_column(String(32),default="English"); status: Mapped[str]=mapped_column(String(32)); contact_number: Mapped[str|None]=mapped_column(String(32)); message: Mapped[str]=mapped_column(Text); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); sent_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); failed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); failure_reason: Mapped[str|None]=mapped_column(Text)
class AuditEventModel(Base):
    __tablename__="audit_events"; __table_args__=(Index("ix_audit_case_timestamp","case_id","timestamp"),Index("ix_audit_merchant_timestamp","merchant_id","timestamp")); id: Mapped[str]=mapped_column(String(64),primary_key=True); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); event_type: Mapped[str]=mapped_column(String(64)); case_id: Mapped[str|None]=mapped_column(ForeignKey("cases.id",ondelete="RESTRICT")); campaign_id: Mapped[str|None]=mapped_column(ForeignKey("campaigns.id",ondelete="RESTRICT")); recovery_action_id: Mapped[str|None]=mapped_column(ForeignKey("recovery_actions.id",ondelete="RESTRICT")); policy_version: Mapped[str|None]=mapped_column(String(32)); actor: Mapped[str]=mapped_column(String(100)); timestamp: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); metadata_json: Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class EvaluationRunModel(Base):
    __tablename__="evaluation_runs"; id: Mapped[str]=mapped_column(String(64),primary_key=True); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); status: Mapped[str]=mapped_column(String(32)); metrics: Mapped[dict]=mapped_column(JSON); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class FailureEventModel(Base):
    __tablename__="failure_events"; id: Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); service: Mapped[str]=mapped_column(String(64)); scenario: Mapped[str]=mapped_column(String(64)); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class WebhookEventModel(Base):
    __tablename__="webhook_events"; __table_args__=(UniqueConstraint("merchant_id","event_id",name="uq_webhook_merchant_event"),Index("ix_webhook_merchant_event","merchant_id","event_id")); id: Mapped[str]=mapped_column(String(64),primary_key=True,default=uid); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); provider: Mapped[str]=mapped_column(String(32),default="razorpay"); event_id: Mapped[str]=mapped_column(String(128)); event_type: Mapped[str]=mapped_column(String(64)); payload: Mapped[dict]=mapped_column(JSON); processed: Mapped[bool]=mapped_column(Boolean,default=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow)
class RecoveryBatchModel(Base):
    __tablename__="recovery_batches"; __table_args__=(UniqueConstraint("merchant_id","idempotency_key",name="uq_batch_merchant_key"),Index("ix_batch_merchant_status","merchant_id","status"),Index("ix_batch_merchant_created","merchant_id","created_at")); id: Mapped[str]=mapped_column(String(64),primary_key=True); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); status: Mapped[str]=mapped_column(String(32),default="PREVIEW"); idempotency_key: Mapped[str]=mapped_column(String(255)); selection_criteria: Mapped[dict]=mapped_column(JSON,default=dict); batch_size: Mapped[int]=mapped_column(Integer,default=0); total_revenue_at_risk_minor: Mapped[int]=mapped_column(Integer,default=0); eligible_revenue_minor: Mapped[int]=mapped_column(Integer,default=0); blocked_revenue_minor: Mapped[int]=mapped_column(Integer,default=0); attempted_recovery_minor: Mapped[int]=mapped_column(Integer,default=0); recovered_revenue_minor: Mapped[int]=mapped_column(Integer,default=0); failed_recovery_minor: Mapped[int]=mapped_column(Integer,default=0); pending_recovery_minor: Mapped[int]=mapped_column(Integer,default=0); cases_selected: Mapped[int]=mapped_column(Integer,default=0); cases_eligible: Mapped[int]=mapped_column(Integer,default=0); cases_blocked: Mapped[int]=mapped_column(Integer,default=0); cases_attempted: Mapped[int]=mapped_column(Integer,default=0); cases_recovered: Mapped[int]=mapped_column(Integer,default=0); cases_failed: Mapped[int]=mapped_column(Integer,default=0); cases_pending: Mapped[int]=mapped_column(Integer,default=0); ai_analysis: Mapped[dict|None]=mapped_column(JSON,nullable=True); summary_metadata: Mapped[dict|None]=mapped_column(JSON,nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); started_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); completed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); cancelled_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
class RecoveryBatchItemModel(Base):
    __tablename__="recovery_batch_items"; __table_args__=(UniqueConstraint("batch_id","case_id",name="uq_batch_item_batch_case"),Index("ix_batch_item_case","case_id"),Index("ix_batch_item_batch","batch_id")); id: Mapped[str]=mapped_column(String(64),primary_key=True,default=uid); batch_id: Mapped[str]=mapped_column(ForeignKey("recovery_batches.id",ondelete="CASCADE")); case_id: Mapped[str]=mapped_column(ForeignKey("cases.id",ondelete="RESTRICT")); merchant_id: Mapped[str]=mapped_column(ForeignKey("merchants.id",ondelete="RESTRICT")); priority_score: Mapped[int]=mapped_column(Integer,default=0); priority_tier: Mapped[str]=mapped_column(String(16),default="Medium"); amount_minor: Mapped[int]=mapped_column(Integer,default=0); expected_recovery_minor: Mapped[int]=mapped_column(Integer,default=0); policy_allowed: Mapped[bool]=mapped_column(Boolean,default=True); blocked_rules: Mapped[dict|list]=mapped_column(JSON,default=list); recommended_intervention: Mapped[str]=mapped_column(String(64),default="RETRY_PAYMENT"); strategy: Mapped[str]=mapped_column(String(64),default="retry_payment"); decision_source: Mapped[str]=mapped_column(String(32),default="DETERMINISTIC_FALLBACK"); status: Mapped[str]=mapped_column(String(32),default="PENDING"); recovery_action_id: Mapped[str|None]=mapped_column(ForeignKey("recovery_actions.id",ondelete="SET NULL"),nullable=True); execution_error: Mapped[str|None]=mapped_column(Text,nullable=True); created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow); executed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True)
