import { FailureScenarioConfig } from "./types";

export const FAILURE_SCENARIOS: FailureScenarioConfig[] = [
  {
    id: "SCEN_POLICY_DOWN",
    title: "Scenario 1: Policy Engine Unavailable (Safe Pause)",
    description: "Simulates deterministic policy validation engine going offline. RECLAIM must refuse financial actions until policy checking is restored.",
    failureType: "POLICY_FAILURE",
    severity: "CRITICAL",
    targetService: "POLICY_ENGINE",
    simulatedError: "Policy service unreachable (HTTP 503)",
    expectedState: "PAUSED / BLOCKED",
    financialImpact: "₹0 false recovery (Safety verified)",
    recoveryPath: "Retry Policy Check → Policy Restored → Case Ready",
  },
  {
    id: "SCEN_EXECUTOR_DECLINE",
    title: "Scenario 2: Gateway Executor Hard Decline",
    description: "Simulates issuing bank rejecting automated retry challenge. RECLAIM isolates failure, preserves ₹0 recovery, and triggers fallback or escalation.",
    failureType: "EXECUTION_FAILURE",
    severity: "HIGH",
    targetService: "RECOVERY_EXECUTOR",
    simulatedError: "Issuing bank declined retry authorization",
    expectedState: "FAILED → FALLBACK / ESCALATED",
    financialImpact: "₹0 false recovery (Accurate accounting)",
    recoveryPath: "Evaluate fallback strategy or route to VIP Customer Desk",
  },
  {
    id: "SCEN_VERIFY_TIMEOUT",
    title: "Scenario 3: Gateway Verification Timeout (Outcome Unknown)",
    description: "Simulates ambiguous gateway response after 30s. RECLAIM marks state as OUTCOME_UNKNOWN, prevents duplicate debits, and waits for confirmation.",
    failureType: "VERIFICATION_TIMEOUT",
    severity: "HIGH",
    targetService: "VERIFICATION_SERVICE",
    simulatedError: "Webhook telemetry unconfirmed after 30s",
    expectedState: "OUTCOME_UNKNOWN → ESCALATED",
    financialImpact: "₹0 recorded until verified settlement",
    recoveryPath: "Retry Verification Telemetry or Escalate to Finance Queue",
  },
  {
    id: "SCEN_AUDIT_DOWN",
    title: "Scenario 4: Audit Service Down (Traceability Protection)",
    description: "Simulates immutable audit ledger connection drop. RECLAIM refuses to perform unlogged financial actions.",
    failureType: "AUDIT_FAILURE",
    severity: "CRITICAL",
    targetService: "AUDIT_SERVICE",
    simulatedError: "Audit datastore connection lost",
    expectedState: "ACTION_BLOCKED_FOR_SAFETY",
    financialImpact: "₹0 false recovery (Strict compliance)",
    recoveryPath: "Restore Audit Service → User Explicitly Retries",
  },
  {
    id: "SCEN_COMM_DOWN",
    title: "Scenario 5: Communication Channel Failure",
    description: "Simulates WhatsApp Business API rate limit / drop. RECLAIM halts messaging, protects customer contact cap, and evaluates alternative SMS.",
    failureType: "COMMUNICATION_FAILURE",
    severity: "MEDIUM",
    targetService: "COMMUNICATION_SERVICE",
    simulatedError: "WhatsApp Business gateway 429 Too Many Requests",
    expectedState: "COMMUNICATION_FAILED",
    financialImpact: "₹0 false recovery (Zero spam)",
    recoveryPath: "Switch to SMS Nudge or Escalate",
  },
  {
    id: "SCEN_DUPLICATE_TRIGGER",
    title: "Scenario 6: Rapid Duplicate Request Interception",
    description: "Simulates merchant double-clicking 'Execute Recovery'. Idempotency lock intercepts second trigger and prevents double debit.",
    failureType: "DUPLICATE_REQUEST",
    severity: "LOW",
    targetService: "RECOVERY_EXECUTOR",
    simulatedError: "Concurrent duplicate idempotency token detected",
    expectedState: "DUPLICATE_PREVENTED",
    financialImpact: "₹0 duplicate loss",
    recoveryPath: "Single active transaction proceeds safely",
  },
  {
    id: "SCEN_CAMPAIGN_PARTIAL",
    title: "Scenario 7: Partial Campaign Failure Isolation",
    description: "Simulates one case failing mid-campaign. RECLAIM isolates the failure, logs the exception, and continues processing remaining cases.",
    failureType: "CAMPAIGN_FAILURE",
    severity: "HIGH",
    targetService: "CAMPAIGN_ORCHESTRATOR",
    simulatedError: "Isolated case execution failure in batch",
    expectedState: "PARTIALLY_RECOVERED (Isolated)",
    financialImpact: "Only verified recoveries settled",
    recoveryPath: "Batch completes without cascading crash",
  },
  {
    id: "SCEN_CAMPAIGN_DOWN",
    title: "Scenario 8: Campaign Orchestrator Interruption & Resume",
    description: "Simulates batch runner interruption. Campaign pauses safely with progress intact, then resumes idempotently upon restoration.",
    failureType: "CAMPAIGN_FAILURE",
    severity: "HIGH",
    targetService: "CAMPAIGN_ORCHESTRATOR",
    simulatedError: "Orchestrator worker paused",
    expectedState: "PAUSED → RESUMED",
    financialImpact: "Zero duplicate processing",
    recoveryPath: "Resume Campaign → Idempotent re-check",
  },
];
